apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nginx-app.clusterRoleBindingName" . }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nginx-app.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io

